#!/bin/bash

## Install packages for myself ####
read -n1 -rep 'Would you like to install the packages? (y,n)' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
  sudo pacman -S wayland wayland-protocols wlroots0.19 alacritty \
  base-devel git firefox swaybg ttf-jetbrains-mono-nerd bluez \
  bluez-utils pamixer pulseaudio-bluetooth thunar starship fish \
  brightnessctl kmix obsidian xpdf tllist fcft pixman bluetui \
  vlc vlc-plugin-ffmpeg

  echo -e "Main packages installed...\n"
  sleep 2
  echo -e "Installing YAY for AUR helper...\n"
  sleep 2
  
  cd Install/
  git clone https://aur.archlinux.org/yay.git
  cd yay
  makepgk -si

  echo -e "YAY has been installed...\n"
  # CD out of YAY folder
  cd ..
  # CD Back to primary folder
  cd ..
  sleep 2
  yay -S fuzzel

  sudo systemctl enable --now bluetooth.service
fi

### Copy Config Files ###
read -n1 -rep 'Would you like to copy config files? (y,n)' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
    echo -e "Copying config files...\n"
    mkdir ~/.config
    mkdir ~/.scripts
    mkdir ~/.install
    mkdir ~/Desktop
    mkdir ~/Documents
    mkdir ~/Videos
    mkdir ~/Photos
    
    cp -r /Config/ ~/.config/
    cp -r /Scripts/ ~/.scripts/

    cp -r /Install ~/.install

    cp Scripts/start_dwl.sh ~/

    sudo chmod +x ~./start_dwl.sh
    sudo chmod +x ~/.scripts/volume.sh

    cd ~/.install/dwl
    sudo make clean install
    cd ~/.install/slstatus
    sudo make clean install
fi

### Script is done ###
echo -e "Script had completed...\n"
