#!/bin/bash

## Install packages for myself ####
read -n1 -rep 'Would you like to install the packages? (y,n)' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
  sudo pacman -S wayland wayland-protocols wlroots0.19 alacritty \
  base-devel git firefox swaybg ttf-jetbrains-mono-nerd bluez \
  bluez-utils pamixer pulseaudio-bluetooth thunar starship fish \
  brightnessctl kmix obsidian xpdf tllist fcft pixman bluetui \
  vlc vlc-plugin-ffmpeg helix

  echo -e "Main packages installed...\n"
  sleep 2
  echo -e "Installing YAY for AUR helper...\n"
  sleep 2
  
  cd Install/
  git clone https://aur.archlinux.org/yay.git

  sleep 5
  cd yay
  makepkg -si

  sleep 2
  
  echo -e "YAY has been installed...\n"
  # CD out of YAY folder
  cd ~/DWL-DE
  sleep 2
  yay -S fuzzel

  sudo systemctl enable --now bluetooth.service
fi

### Copy Config Files ###
read -n1 -rep 'Would you like to copy config files? (y,n)' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
    echo -e "Copying config files...\n"
    mkdir ~/.scripts
    mkdir ~/.install
    mkdir ~/Desktop
    mkdir ~/Documents
    mkdir ~/Videos
    mkdir ~/Photos

   cp -r Configs/alacritty ~/.config
   cp -r Configs/background ~/.config
   cp -r Configs/fish ~/.config
   cp -r Configs/fuzzel ~/.config
   cp -r Configs/helix ~/.config
   cp Configs/starship.toml ~/.config

   cp -r Install/dwl ~/.install
   cp -r Install/slstatus ~/.install

    cp Scripts/start_dwl.sh ~/
    cp Scripts/volume.sh ~/.scripts

    sudo chmod +x ~./start_dwl.sh
    sudo chmod +x ~/.scripts/volume.sh

    cd ~/.install/dwl
    sudo make clean install

    sleep 2
    cd ~/.install/slstatus
    sudo make clean install
fi

### Script is done ###
echo -e "Script had completed...\n"
